# Список id админов
admins_id = [] # Сюда ID админов
# Основные параметры
bot_token = "Ваш токен бота"
chat_id = "ID вашей группы"
# Время мута в секундах
fun_mute_time = 30
spam_mute_time = 3600
mute_up = 120
# Количество сообщений для мута и количество мутов для бана
number_of_messages = 20
number_of_repetitions = 4
# Тригеры
triggers = {
    ("лялекс", "луних", "лялех", "люнех", "люникс", "линех", "lalix", "linups", "линупс", "линх", "люнекс"): "— Hello, this is Linus Torvalds, and I pronounce Linux as [ˈlɪnʊks].",
    ("бан", "ban", ",fy", "фу"): "Жан Клод Вам Бан",
    ("блина",): "«Индекс блина» в России за год упал на 9%",
    ("manjaro", "манджаро", "манжаро", "манжара", "манджара"): 'Короче, <a href="tg://user?id={}">{}</a>, я тебя в чате приютил, но в благородство играть не буду: поставь лучше арч — и мы в расчете. Заодно посмотрим, как быстро у тебя башка после такого дистра прояснится. А по твоей теме даже разузнать не попытаюсь. Хрен его знает, на кой ляд тебе эта манжара сдалась, но я в чужие дела не лезу, хочешь юзать, значит юзай, тут не со мной консультироваться надо...',
}
# Приветствие
welcome_text = """Приветствуем тебя в <b>Linux Sucks</b>, <a href="tg://user?id={}">{}</a>! 
Мы здесь чтобы спорить о *nix системах, делиться опытом, просто общаться и иногда решать проблемы и помогать друг другу. Присоединяйся и развивайся с нами!"""
# Правила чата
rules_text = """<b>Правила LinuxSucks</b>
0. Чат создан не для техподдержки, а прежде всего для уважительного общения.
1. Относитесь друг к другу уважительно.
2. Мат разрешен, но не в оскорбительном тоне.
3. Любой спор не должен перетекать в оскорбления и/или троллинг.
4. Избегайте размещения nsfw контента (https://ru.wikipedia.org/wiki/NSFW).
5. Любой спам / флуд / шитпостинг запрещены.
6. Любые проявления нетерпимости ставят вас под угрозу бана, имейте это ввиду.
Вопросы задавать можно, но стоит научиться делать это правильно - https://nometa.xyz/"""
# Список стикеров
stikers = ["CAACAgIAAxkBAAEF2mVfSAd763n-FI5L2Vr8loOWtInJ0AACJAADqYi0DGfeAAFpEPTmDhsE",
           "CAACAgIAAxkBAAEF4tdfTA0kAyxIUIOAHk131XPxB6Ic1AACDQADqYi0DMzQKS5d8hF9GwQ",
           "CAACAgIAAxkBAAIdmF9-slZV9F9zJ5AEWEx6qJqxBou-AAIMAAOpiLQM77qc_i347bUbBA",
           "CAACAgIAAxkBAAIdm19-snkj9LY58ktaUlUZhK8gM19GAAIOAAOpiLQMJ44a3eW7Op4bBA",
           "CAACAgIAAxkBAAIdnl9-soaXEPpB7vTYT5592kRTmVv6AAIPAAOpiLQMxav1WkU_MRQbBA",
           "CAACAgIAAxkBAAIdoV9-spUqTwwUYGWHyxb2b1dHwGqUAAIQAAOpiLQME6X3rXftzogbBA",
           "CAACAgIAAxkBAAIdpF9-sqPm0YlWNlgkPMOJNLrBUJUKAAIRAAOpiLQMIiMBEOktUKEbBA",
           "CAACAgIAAxkBAAIdp19-srt9YVS3akra8I8QPbx_Zb66AAISAAOpiLQMpnDen4kcDakbBA",
           "CAACAgIAAxkBAAIdql9-ssgbpjEbqS8Q0cFS-liUmYXQAAITAAOpiLQMSmhnGOS4MnAbBA",
           "CAACAgIAAxkBAAIdrV9-stU--yg_kDblwGxfAb4okf4lAAIUAAOpiLQM88jrEfIiiG0bBA",
           "CAACAgIAAxkBAAIdsF9-suEZHQU8hsf-A6OcrP-dmQm9AAIVAAOpiLQM8aaTxLG1tSMbBA",
           "CAACAgIAAxkBAAIds19-su-cMiS0rzEUAm2_GfM9wSnbAAIWAAOpiLQMjtLvYp4lHM4bBA",
           "CAACAgIAAxkBAAIdtl9-svzYlQkg-zd4EVNdWyTEtJH9AAIYAAOpiLQMNhbQNiiWOQ0bBA",
           "CAACAgIAAxkBAAIduV9-swoqzPx1gTP5DOL-oPYq8wfNAAIZAAOpiLQM_PJ-d7WPyVQbBA",
           "CAACAgIAAxkBAAIdvF9-sxXeRK4HFHC109_oP_Te7O2RAAIaAAOpiLQM9yj85HypZ-0bBA",
           "CAACAgIAAxkBAAIdv19-syRJ3VuzWGareqXI_nyFF5lDAAIbAAOpiLQMNmqYulHySZIbBA",
           "CAACAgIAAxkBAAIdwl9-szInkbNO47ocPPl4nZiUKfOBAAIdAAOpiLQMn3u1yPUbvW4bBA",
           "CAACAgIAAxkBAAIdxV9-sz4Ti_DasQz7WpPIwfwyT23PAAIeAAOpiLQMsbln1Kn1Hy0bBA",
           "CAACAgIAAxkBAAIdyF9-s0wfGftoviTLfIUs6DFkAe2lAAIfAAOpiLQMpkHh2QN43esbBA",
           "CAACAgIAAxkBAAIdy19-s1nv9TxdAimpGz-jnfoK27rvAAIgAAOpiLQMfsHLbWQonDwbBA",
           "CAACAgIAAxkBAAIdzl9-s2VKOgWptyQ92SIYGZTbj_aaAAIhAAOpiLQMLjbD6KNg8FEbBA",
           "CAACAgIAAxkBAAId0V9-s3JYveedOAl5QcpGmtKlMB8AAyIAA6mItAyAAykGNW7nNhsE",
           "CAACAgIAAxkBAAId1F9-s5pjOO14yAotVH5tvtSY7XnnAAIjAAOpiLQMuMUOZnyg3X0bBA",
           "CAACAgIAAxkBAAId2l9-s6g3JHAx3pJbnBKlZeRtSkgfAAIlAAOpiLQM4TTHRui990kbBA",
           "CAACAgIAAxkBAAId3V9-s7TfO0wdnZgFwq8j-zn7Hj_fAAImAAOpiLQMpWoGmaG-ZJMbBA",
           "CAACAgIAAxkBAAId4F9-s8EtjlPZMeNJ4TCYGI4ZP7cvAAInAAOpiLQMVJdJGjqvj_obBA",
           "CAACAgIAAxkBAAId419-s84WHDQV5pMOpf665bkAAclhBAACKAADqYi0DPmVFd9Fnd8AARsE",
           "CAACAgIAAxkBAAId5l9-s9l4v_ju2DaNiDqo2L-7WbD2AAIpAAOpiLQMTUvWZvQYxXUbBA",
           "CAACAgIAAxkBAAId6V9-s_XBqbe06fSZcCpF0ODAHPMUAAIqAAOpiLQMXLALJ6G_iq8bBA",
           "CAACAgIAAxkBAAId7F9-teD8q0RDHUINRjj83RcXTzQcAAIrAAOpiLQMtZxsckPPnpwbBA",
           "CAACAgIAAxkBAAId719-te1U5LZ7kq4m1AyO3dP8XmF9AAIsAAOpiLQMSi5mqhAqvMQbBA",
           "CAACAgIAAxkBAAId8l9-tfjWkwtjWBLwi8FRLP3vo8qbAAIuAAOpiLQM1GsSwpe4uBgbBA",
           "CAACAgIAAxkBAAId9V9-tgoPX31oOC47YEYzx1boRWJ8AAIvAAOpiLQMFcEWz3lLO10bBA",
           "CAACAgIAAxkBAAId-F9-tkxoIEt4nXL91_4GIxYJ2S5MAAIwAAOpiLQMVXf1caMZq7AbBA",
           "CAACAgIAAxkBAAId-19-tlvs6Sq9BjvzLFRk8i8WVZBBAAIxAAOpiLQMoBpXZgABj7t0GwQ",
           "CAACAgIAAxkBAAId_l9-tm34aPmfCGJHkbWpV_c58hxCAAIyAAOpiLQMDno6aHEWDNIbBA",
           "CAACAgIAAxkBAAIeAV9-tnlUKlYcgqICBZGmrAqj1EcAAzMAA6mItAw74Q_0Y5yL5hsE",
           "CAACAgIAAxkBAAIeBF9-toSvTRbUyAMlVZvaMw62kDgtAAI0AAOpiLQMIRYfT2D6NpMbBA",
           "CAACAgIAAxkBAAIeB19-tpLapDdyGIl62G-o8I6WnW9tAAI1AAOpiLQMA78u0-sJi9QbBA",
           "CAACAgIAAxkBAAIeCl9-trHM5zf0nZDJBeK0nwlNASUsAAI3AAOpiLQMsaY6XDzeomkbBA",
           "CAACAgIAAxkBAAIeDV9-tr0GoudWYysrgOfILFUydrM3AAI5AAOpiLQMK5vZhAUbtyQbBA",
           "CAACAgIAAxkBAAIeEF9-tsd9MVOc-hKxP00B7Df6ufu3AAI6AAOpiLQM2WUm1BjaQ18bBA",
           "CAACAgIAAxkBAAIeE19-ttJr__oYStYx0pgUN6Edu3FkAAI7AAOpiLQMNwOJLmWNonwbBA",
           "CAACAgIAAxkBAAIeFl9-tt0dLYS4gfyeywFQXOqPaFBhAAI8AAOpiLQM09BLWqTOzvkbBA",
           "CAACAgIAAxkBAAIeGV9-tujAhrJXxHsI4M7LDzJyKHIuAAI9AAOpiLQMdK_GRljKSu4bBA",
           "CAACAgIAAxkBAAIeHF9-tw0vPw02M8dmjR67DJaYQ5YxAAI-AAOpiLQMcTFu28a0TBIbBA",
           "CAACAgIAAxkBAAIeH19-tx49D1dm8qFx6837ow9MJhDaAAI_AAOpiLQM3ShXjVcdbHQbBA",
           "CAACAgIAAxkBAAIeIl9-tzLwqbaIiYoikhvr4LwnIpD9AAJAAAOpiLQM1rgt7JhZPKwbBA",
           "CAACAgIAAxkBAAIeJV9-tz3YbXRaEUqQrlJQ9G5dqsV5AAJCAAOpiLQMdhowOfCUjA4bBA",
           "CAACAgIAAxkBAAIeKF9-t0mZJ0tJoHK5SQABUJjJ8mJ1lAACQwADqYi0DD9YEh45r2MbGwQ",
           "CAACAgIAAxkBAAIeK19-t1iJFCp5oU0O16PNzY8hMsRpAAJEAAOpiLQMTM8tDbKvcWIbBA",
           "CAACAgIAAxkBAAIeLl9-t2QqAYpGhNH2AmLh7Tu03C8HAAJFAAOpiLQMpUa-8kffN_gbBA",
           "CAACAgIAAxkBAAIeMV9-t3LOS9w9YPg6TSWTo1rpdhfcAAJGAAOpiLQM6y58PsR2EvgbBA",
           "CAACAgIAAxkBAAIeNF9-t3-yxnagsvAvsDmKAVnY8DZkAAJHAAOpiLQMD0LqPm70_owbBA",
           "CAACAgIAAxkBAAIeN19-t4s8vTwib8t5yOeRGYPfqfsNAAJJAAOpiLQM08jP6qQomSgbBA",
           "CAACAgIAAxkBAAIeOl9-t6BppyyPO4602eiWOQENc0hbAAJKAAOpiLQMRJbAj0Q3u3sbBA",
           "CAACAgIAAxkBAAIePV9-t69woBIJsYGdiUDcBt4MeSpQAAJLAAOpiLQMrk3odeCxcTsbBA",
           "CAACAgIAAxkBAAIeQF9-t7vsQdkK2gtjmq2ClMk1aagJAAJMAAOpiLQMK3pTnTBbq7QbBA",
           "CAACAgIAAxkBAAIeQ19-t8V5VO18Iebwup_rBVanp8gSAAJNAAOpiLQMggpSZx0rqVobBA",
           "CAACAgIAAxkBAAIeRl9-t9GUb2M4xe_vKJl50Guil43yAAJOAAOpiLQMuNbaAzqtZUsbBA",
           "CAACAgIAAxkBAAIeSV9-t9wQQ3-2lRdGnudkkMQMDqqzAAJPAAOpiLQMhbFpzxNVAdcbBA",
           "CAACAgIAAxkBAAIeTF9-uAXI9VSpj5Rlz_Clfzjp4NAQAAJQAAOpiLQMrtNerTVyhuAbBA",
           "CAACAgIAAxkBAAIeT19-uBA9A49sPobTnAqs3vjZRn4fAAJRAAOpiLQM7nQ0euEZwAsbBA",
           "CAACAgIAAxkBAAIeUl9-uBnAnBpyph6lk1ZGlNb_fHv1AAJSAAOpiLQMcKUCTGDX-ogbBA",
           "CAACAgIAAxkBAAIeVV9-uCODuRHGb1CpI2KfWqVdxxTaAAJTAAOpiLQM7PMUakcbEykbBA",
           "CAACAgIAAxkBAAIeWF9-uC5UbWvTyvlG-_QW09EwrMomAAJUAAOpiLQMg5oQm8WlDMEbBA",
           "CAACAgIAAxkBAAIeW19-uDn_fD29kq16QtusE9m95yB2AAJVAAOpiLQMrXEEe85FGY8bBA",
           "CAACAgIAAxkBAAIeXl9-uEMSVUw-yndHiJecRuKNtXlOAAJWAAOpiLQMeVkSycP7FrAbBA",
           "CAACAgIAAxkBAAIeYV9-uE7R0UIkNnNdBSivW6ujGSVvAAJXAAOpiLQM5LkAAavSznKSGwQ",
           "CAACAgIAAxkBAAIeZF9-uFjlGI8vAAHYULlkcxzUmDD6PAACWAADqYi0DEBhC5y_4jLbGwQ",
           "CAACAgIAAxkBAAIeZ19-uHvaYP63UbJjI-S3KuWI14_KAAJZAAOpiLQM2JvbbaCmeNgbBA",
           "CAACAgIAAxkBAAIeal9-uIg82hnameuQLmnXF9FRysB6AAJaAAOpiLQMZ4MYLAQGJtcbBA",
           "CAACAgIAAxkBAAIebV9-uJWb0hLqW73T7PhmeEOFZ85DAAJbAAOpiLQMGaegjSxgHOQbBA",
           "CAACAgIAAxkBAAIecF9-uKCTjgsKzXVA-KMQxOh8FPrfAAJcAAOpiLQMktYGDrgdSy4bBA",
           "CAACAgIAAxkBAAIec19-uKuPn-N39-r5cEvxteXfCX0EAAJdAAOpiLQMxRc4C6UnIDsbBA",
           "CAACAgIAAxkBAAIedl9-uLncnmGNNvxon_85konrjaHEAAJeAAOpiLQMd5luUdAQVsUbBA",
           "CAACAgIAAxkBAAIeeV9-uMSK8DsWKDaGf9AAATycrLcV7AACXwADqYi0DHkeSCgEMWMcGwQ",
           "CAACAgIAAxkBAAIefF9-uNEOFWE-X6Kxx1pvIokTTgqAAAJgAAOpiLQM17KBSfggWokbBA",
           "CAACAgIAAxkBAAIef19-uN03mTnRah18W_VYgY7gwtJoAAJhAAOpiLQMTMEeSivqITEbBA",
           "CAACAgIAAxkBAAIegl9-uOsZsAMydMQ02vime66Q4n5FAAJiAAOpiLQMNbp3LSy8Xq0bBA",
           "CAACAgIAAxkBAAIehV9-uPaP5IO7y9Ask_qA6ulACfOLAAJjAAOpiLQM5ssgPnShCtwbBA",
           "CAACAgIAAxkBAAIeiF9-uQHy5tbcflzAyrM2Ha3HoFhkAAJkAAOpiLQMs1WcAAHjQxHIGwQ",
           "CAACAgIAAxkBAAIei19-uQwHHSWx7cQkcwABIv39gLgiUQACZQADqYi0DE74tmgTBeyoGwQ",
           "CAACAgIAAxkBAAIejl9-uRc9eK7TmuvDVdS_pi8hK8VJAAJmAAOpiLQMvHVMeh3QkQsbBA",
           "CAACAgIAAxkBAAIekV9-uSOFBKjnKgLqSBMt4jM5NVLtAAJoAAOpiLQMqo554aZQIWYbBA",
           "CAACAgIAAxkBAAIelF9-uS4IZbJU8A9ClrjtYWHTVLabAAJpAAOpiLQMPnaMudHxyBUbBA",
           "CAACAgIAAxkBAAIel19-uTg1iXETG-1Qx1ssyUCcmNkdAAJqAAOpiLQMqte8qf-B4VYbBA",
           "CAACAgIAAxkBAAIeml9-uUJDXXMZXZY1WdWrLD4IwwP7AAJrAAOpiLQMmzttztnqq_IbBA",
           "CAACAgIAAxkBAAIenV9-uU2lP6dSoPuJX7spHwsIvQPGAAJsAAOpiLQM8M3G8XS2dUYbBA",
           "CAACAgIAAxkBAAIeoF9-uVZiPgO373GX6CGWsvySAfJbAAJtAAOpiLQMnyifi1K0MlAbBA",
           "CAACAgIAAxkBAAIeo19-uWJf-aqh8-emuAE3dkfv9oqIAAJuAAOpiLQMLJuHLCzccA4bBA",
           "CAACAgIAAxkBAAIepl9-uWzM9ZxAWad4i0dLnQbwf7IxAAJvAAOpiLQM1Ge7jOUOlSgbBA",
           "CAACAgIAAxkBAAIeqV9-uXjXWR4RnPsoFrZGNlpQmDM5AAJwAAOpiLQMhN8-E9pLYbsbBA",
           "CAACAgIAAxkBAAIerF9-uYIlkxKbqccIF2V5g8CsI_wnAAJxAAOpiLQMOog74vbaiFIbBA",
           "CAACAgIAAxkBAAIer19-uYyrW1RGaRMzDVuhVd1jFefwAAJyAAOpiLQMXrfn1-XxyisbBA",
           "CAACAgIAAxkBAAIesl9-uZeO7QtsuE5H8sfWef3rS-B_AAJzAAOpiLQMnoYoUbmI78QbBA",
           "CAACAgIAAxkBAAIetV9-uaJKS6qI_X3LqAsfQZsnzhIoAAJ0AAOpiLQMuYv4xWeRxMUbBA",
           "CAACAgIAAxkBAAIeuF9-ua4b8_QAAc38UrKtvOxTZw28YgACdQADqYi0DIFttpE4ytjEGwQ",
           "CAACAgIAAxkBAAIeu19-ubkNea-u0M-YaXNDGCZGomBsAAJ2AAOpiLQMZgLMKVe1Y4obBA",
           "CAACAgIAAxkBAAIevl9-ucWbvO-ShDLGeTFdeuKSkns5AAJ3AAOpiLQM4r5LxV6nahsbBA",
           "CAACAgIAAxkBAAIewV9-uc-2vi8eyiRTJqt7fs8fiGkHAAJ5AAOpiLQMIVsS08-IbKwbBA",
           "CAACAgIAAxkBAAIexF9-udkAAYYdTIpabpQMhoOT-J_PTAACegADqYi0DPqDheMEy5TCGwQ",
           "CAACAgIAAxkBAAIex19-ueMlds0idJ83aext4WMFrtnUAAJ7AAOpiLQMnclwr6AwxFsbBA",
           "CAACAgIAAxkBAAIeyl9-ue2uS6o3Sb9Sicei0umVIn5cAAJ8AAOpiLQM2uGjDXU5xeEbBA",
           "CAACAgIAAxkBAAIezV9-ufZLneg5um2e4j6tNJfw9BQeAAJ9AAOpiLQM7XCKR10hsEEbBA",
           "CAACAgIAAxkBAAIe0F9-ugH8OFn0OoZIzd3d_54rcxJwAAJ-AAOpiLQMulJ8H_2_WNwbBA",
           "CAACAgIAAxkBAAIe019-ug2-G8ADNHcrWBouWVVfiUg7AAKAAAOpiLQMurT5SQ0bVOIbBA",
           "CAACAgIAAxkBAAIe1l9-uhalSgPOtd-yvfW39CgOQGS7AAKBAAOpiLQMwHOOKTS82hYbBA",
           "CAACAgIAAxkBAAIe2V9-uh8QDW0C75ff-hg2z2ko7T3VAAKCAAOpiLQMG5P5ws_3_aQbBA",
           "CAACAgIAAxkBAAIe3F9-uiqqXgnB7B_dM70sPNhOkImBAAKDAAOpiLQMWZ-UU6LQkmsbBA",
           "CAACAgIAAxkBAAIe319-ujV4Es3Wcf5hwc7OaR5_v-sSAAKEAAOpiLQMBxeXyGKwZBEbBA",
           "CAACAgIAAxkBAAIe4l9-ukCo_1WZCX8Ks3-C8A841PjxAAKGAAOpiLQMYbRanN2nl0UbBA",
           "CAACAgIAAxkBAAIe5V9-ukugsp7zWmQys1BFAz4dx0HgAAKHAAOpiLQM868trcb9fcEbBA",
           "CAACAgIAAxkBAAIe6F9-ulbp-HGLhb8j1uSRZcHgG2OiAAKIAAOpiLQMvVpov3KZn_wbBA",
           "CAACAgIAAxkBAAIe619-umKQnhCtP8svqttcjErvLaVMAAKJAAOpiLQMOy302KnAYXgbBA",
           "CAACAgIAAxkBAAIe7l9-unEWBY0vRhnKSsnJs1yPFL0vAAKsAAOpiLQM6pMsMOZVz0YbBA",
           "CAACAgIAAxkBAAIe8V9-unuif1kirv6gIkoPA5vjq3jzAAKtAAOpiLQMjsdhZFtjGhobBA",
           "CAACAgIAAxkBAAIe9F9-uoUOXFDcotbN3QeT2GbEYUPpAALIAAOpiLQM70kKyi5LTMsbBA",
           "CAACAgIAAxkBAAIfEl9--0MXbIfa6SW2RTu5QERtp3WtAAKuAAOpiLQMEVLHgQiDvcsbBA",
           "CAACAgIAAxkBAAIfFV9--4fLKwZE_hSk4ghLVlgCFGS5AAKvAAOpiLQMc1iajveK_u8bBA",
           "CAACAgIAAxkBAAIfGF9--8K_QIj2riWlHvJSi2IFZjg4AAKwAAOpiLQMngORKQABwZGUGwQ",
           "CAACAgIAAxkBAAIfG19--86gJeVbZJgLiE3ekx5o1KTcAAKxAAOpiLQMaFuQ8HNHw8AbBA",
           "CAACAgIAAxkBAAIfHl9--9uXy44GcStSY9gL0wlPKQo1AAKyAAOpiLQMXODFf2t1yG4bBA",
           "CAACAgIAAxkBAAIfIV9---kXn7HLqLgXIQ25vuCdeRgAA7MAA6mItAzY_K5qTrA85RsE",
           "CAACAgIAAxkBAAIfJF9--_z-5SN2XjnPDqE2iyIC5CoHAAK0AAOpiLQMDX9mwhW-hj4bBA",
           "CAACAgIAAxkBAAIfJ19-_AmXlHEHhgG5x2BgXdQlhNnVAAK1AAOpiLQMycT7RKlBixMbBA",
           "CAACAgIAAxkBAAIfKl9-_BQhxWItAAG4RXa2W_2cYv2icQACtwADqYi0DN_lCWhDbow8GwQ",
           "CAACAgIAAxkBAAIfLV9-_B8mi2o4t53cTbGIw5-LCdTgAAK4AAOpiLQMlw_bGE4Qd24bBA",
           "CAACAgIAAxkBAAIfMF9-_CxLFY3tV6lLTgRssTD9y3p2AAK5AAOpiLQMTmxYdWjOAxYbBA",
           "CAACAgIAAxkBAAIfM19-_DrHsTkS5ZHr_LJA39IRql9KAAK7AAOpiLQM4vugz6I-BuUbBA",
           "CAACAgIAAxkBAAIfNl9-_EaZgLyucpCHmHljBBUuVYjWAAK8AAOpiLQMmdgpcbvfUsMbBA",
           "CAACAgIAAxkBAAIfOV9-_FH0SuIZ8nkMGDZh5zcCB2QGAAK9AAOpiLQMHXTyQFumuVAbBA",
           "CAACAgIAAxkBAAIfPF9-_FwxCFXG1tiarbrIGrUAAVLSmgACvgADqYi0DEeca9EaQLcHGwQ",
           "CAACAgIAAxkBAAIfP19-_Gda-KWI65hRzAevXRP57tBqAAK_AAOpiLQM3Z7y-PRv0IsbBA",
           "CAACAgIAAxkBAAIfQl9-_HF6WWCOKB_Qr5yZuBE1YtVeAALAAAOpiLQMsUWlQRaGiNUbBA",
           "CAACAgIAAxkBAAIfRV9-_Hxa1n77AUww-ZeSa4MzaBHBAALBAAOpiLQMDDBJtjSm8RMbBA",
           "CAACAgIAAxkBAAIfSF9-_IaU5zeC3X1BAo6NVID6h8HmAALCAAOpiLQMQguGycN4oK0bBA",
           "CAACAgIAAxkBAAIfS19-_LOgjWmQiyIOrVQYWOGqbTc2AALDAAOpiLQMkwMIf_HdYVUbBA",
           "CAACAgIAAxkBAAIfTl9-_MCjvGaOR1-uMWz7r78C1NeHAALFAAOpiLQMbi2alcS1nTwbBA",
           "CAACAgIAAxkBAAIfUV9-_PAJL5coIFpyl3-1vwMAAWuQFQACxgADqYi0DBPrPjf031TzGwQ",
           "CAACAgIAAxkBAAIfVF9-_PrBb5N_CjphTNxJLyNiz3tkAALHAAOpiLQMRTZmWa1uL4obBA"]
#Всякая буферная фигня
new_user_id = 0
message_id = 0
new_user_name = "none"
