name: tox

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: prepare environment
      run: cp .env.example .env
      
    - name: Install tox
      run: pip install tox
      
    - name: Run tox
      run: python -m tox